# Site settings
title: "OpenMoss Lab"
subtitle: ""
description: "The OpenMoss Lab at Fudan University focuses on large language models, multimodal learning, embodied AI, and contextual intelligence."
baseurl: "/openmosslab" # the subpath of your site, e.g. /blog
url: "https://dalstonchen.github.io" # the base hostname & protocol for your site

# Organization info
organization:
  name: "OpenMoss Lab"
  full_name: "OpenMoss Lab"
  location1: "3 Lane 699, Huafa Road, Xuhui District"
  location2: "Building 2X, No. 2005 Songhu Road, Yangpu District"
  city: "Shanghai, China"
  email: "xpqiu@fudan.edu.cn"
  

# Social links
social:
  github: "https://github.com/openmosslab"
  twitter: "https://twitter.com/openmosslab"

# Navigation
navigation:
  - title: "people"
    url: "/people/"
  - title: "publications"
    url: "/publications/"
  - title: "software"
    url: "/software/"
  - title: "resources"
    url: "/resources/"
  - title: "career"
    url: "/career/"
  - title: "join"
    url: "/join/"

# Build settings
markdown: kramdown
permalink: pretty
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - SETUP.md
  - QUICKSTART.md
  - PROJECT_SUMMARY.md
  - ARCHITECTURE.md
  - DEPLOYMENT_CONFIG.md
  - FIXES_APPLIED.md
  - content.txt
  - "The Stanford Natural Language Processing Group_files"

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
